package ru.stqa.pft.addressbook;// Generated by Selenium IDE

import org.openqa.selenium.JavascriptExecutor;


import org.testng.annotations.*;

public class GroupCreationTest  extends TestBase{
    JavascriptExecutor js;

    @Test
    public void testGroupCreation() {

        gotoGroupPage();
        initGroupCreation();
        fillGroupForm(new GroupData("test1", "test2", "test3"));
        submitGroupCreation();
        returnToGroupPage();
    }

}
